"""
delta_engine.py
Evidence Agent — automatically computes weekly prediction accuracy
and produces evidence_W{XX}.md output file.

Usage:
    python delta_engine.py --week W24
    python delta_engine.py --all
    python delta_engine.py --hardcoded   (runs W24 with built-in data, no files needed)
"""

import json
import argparse
from datetime import date
from pathlib import Path

# ── Configuration ─────────────────────────────────────────────────────────────
PREDICTIONS_DIR = Path("data/predictions")
ACTUALS_DIR     = Path("data/actuals")
DELTA_DIR       = Path("data/delta")
EVIDENCE_DIR    = Path("evidence")

TRACKED_ASSETS  = ["SPX", "NDX", "IWM", "Gold", "WTI", "VIX", "Bitcoin"]

# ── Direction helpers ─────────────────────────────────────────────────────────
def get_direction(change: float) -> str:
    if change > 0.15:  return "UP"
    if change < -0.15: return "DOWN"
    return "FLAT"

def direction_hit(predicted: str, change: float) -> bool:
    actual = get_direction(change)
    if predicted == "UP":        return actual == "UP"
    if predicted == "DOWN":      return actual == "DOWN"
    if predicted == "FLAT-UP":   return actual in ("FLAT", "UP")
    if predicted == "FLAT-DOWN": return actual in ("FLAT", "DOWN")
    if predicted == "FLAT":      return actual == "FLAT"
    return False

def range_hit(low: float, high: float, change: float) -> bool:
    return low <= change <= high

# ── Core computation ──────────────────────────────────────────────────────────
def compute_delta(pred_data: dict, actual_data: dict) -> dict:
    week    = pred_data["week"]
    results = []
    dir_hits = rng_hits = total = 0

    for asset in TRACKED_ASSETS:
        pred   = pred_data["assets"].get(asset)
        actual = actual_data["assets"].get(asset)
        if not pred or not actual:
            continue

        change  = actual["actual_change"]
        p_dir   = pred["direction"]
        p_low   = pred.get("range_low")
        p_high  = pred.get("range_high")

        d_hit = direction_hit(p_dir, change)
        r_hit = range_hit(p_low, p_high, change) if p_low is not None and p_high is not None else None

        results.append({
            "asset":               asset,
            "predicted_direction": p_dir,
            "predicted_range":     f"{p_low}% to {p_high}%" if p_low is not None else "N/A",
            "actual_change":       change,
            "actual_direction":    get_direction(change),
            "direction_hit":       d_hit,
            "range_hit":           r_hit,
        })

        if d_hit: dir_hits += 1
        if r_hit: rng_hits += 1
        total += 1

    return {
        "week":                  week,
        "total_assets":          total,
        "direction_hits":        dir_hits,
        "range_hits":            rng_hits,
        "direction_accuracy_pct": round(dir_hits / total * 100, 1) if total else 0,
        "range_accuracy_pct":    round(rng_hits / total * 100, 1) if total else 0,
        "results":               results,
    }

# ── Evidence .md generator ────────────────────────────────────────────────────
def generate_evidence_md(delta: dict) -> str:
    week     = delta["week"]
    today    = date.today().strftime("%-d %B %Y")
    d_acc    = delta["direction_accuracy_pct"]
    r_acc    = delta["range_accuracy_pct"]
    d_hits   = delta["direction_hits"]
    r_hits   = delta["range_hits"]
    total    = delta["total_assets"]
    results  = delta["results"]

    # Table rows
    rows = ""
    for r in results:
        d_label = "HIT " if r["direction_hit"] else "MISS"
        r_label = "HIT " if r["range_hit"] else ("MISS" if r["range_hit"] is False else "N/A ")
        change  = f"{r['actual_change']:+.2f}%"
        rows += (
            f"| {r['asset']:<20} | {r['predicted_direction']:<10} | {r['predicted_range']:<18} "
            f"| {change:<8} | {d_label} | {r_label} |\n"
        )

    # Missed and hit lists
    misses = [r["asset"] for r in results if not r["direction_hit"]]
    hits   = [r["asset"] for r in results if r["direction_hit"]]

    def row_for(asset):
        r = next(x for x in results if x["asset"] == asset)
        return f"- {asset}: predicted {r['predicted_direction']}, actual {r['actual_change']:+.2f}%"

    miss_block = "\n".join(row_for(a) for a in misses) or "- None"
    hit_block  = "\n".join(row_for(a) for a in hits)   or "- None this week"

    md = f"""Evidence Agent Output — {week} — Auto-generated by delta_engine.py

WEEK: {week}
GENERATED: {today}
EVIDENCE SOURCES: data/predictions/prediction_{week}.json, data/actuals/actuals_{week}.json

---

PREDICTION vs ACTUAL:

| Asset                | Predicted  | Range              | Actual   | Dir  | Range |
|----------------------|------------|--------------------|----------|------|-------|
{rows}
DIRECTIONAL ACCURACY: {d_hits}/{total} ({d_acc}%)
RANGE ACCURACY:       {r_hits}/{total} ({r_acc}%)

---

MISSES ({len(misses)}/{total}):
{miss_block}

HITS ({len(hits)}/{total}):
{hit_block}

---

CALIBRATION SCORE: {d_acc}% directional, {r_acc}% range
NOTE: Auto-generated by delta_engine.py. Add manual notes below if needed.

---

Source: data/predictions/prediction_{week}.json + data/actuals/actuals_{week}.json. Generated: {today}.
"""
    return md

# ── Save functions ────────────────────────────────────────────────────────────
def save_delta_json(delta: dict):
    DELTA_DIR.mkdir(parents=True, exist_ok=True)
    out = DELTA_DIR / f"delta_{delta['week']}.json"
    with open(out, "w") as f:
        json.dump(delta, f, indent=2)
    print(f"Saved delta JSON: {out}")

def save_evidence_md(delta: dict):
    EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
    out = EVIDENCE_DIR / f"evidence_{delta['week']}.md"
    with open(out, "w") as f:
        f.write(generate_evidence_md(delta))
    print(f"Saved evidence MD: {out}")

# ── Print report ──────────────────────────────────────────────────────────────
def print_report(delta: dict):
    week = delta["week"]
    print(f"\n{'='*60}")
    print(f"  DELTA ENGINE — {week}")
    print(f"{'='*60}")
    print(f"  Direction : {delta['direction_hits']}/{delta['total_assets']} ({delta['direction_accuracy_pct']}%)")
    print(f"  Range     : {delta['range_hits']}/{delta['total_assets']} ({delta['range_accuracy_pct']}%)")
    print(f"{'='*60}")
    print(f"  {'Asset':<12} {'Predicted':>10} {'Actual':>10}  Dir   Range")
    print(f"  {'-'*54}")
    for r in delta["results"]:
        d = "HIT " if r["direction_hit"] else "MISS"
        g = "HIT " if r["range_hit"] else ("MISS" if r["range_hit"] is False else "N/A ")
        print(f"  {r['asset']:<12} {r['predicted_direction']:>10} {r['actual_change']:>+9.2f}%  {d}  {g}")
    print(f"{'='*60}\n")

# ── Load from files ───────────────────────────────────────────────────────────
def run_week(week: str):
    pred_file   = PREDICTIONS_DIR / f"prediction_{week}.json"
    actual_file = ACTUALS_DIR / f"actuals_{week}.json"

    if not pred_file.exists():
        raise FileNotFoundError(f"Missing: {pred_file}")
    if not actual_file.exists():
        raise FileNotFoundError(f"Missing: {actual_file}")

    with open(pred_file)   as f: pred_data   = json.load(f)
    with open(actual_file) as f: actual_data = json.load(f)

    delta = compute_delta(pred_data, actual_data)
    print_report(delta)
    save_delta_json(delta)
    save_evidence_md(delta)
    return delta

def run_all():
    if not PREDICTIONS_DIR.exists():
        print(f"Not found: {PREDICTIONS_DIR}")
        return
    files = sorted(PREDICTIONS_DIR.glob("prediction_W*.json"))
    if not files:
        print("No prediction files found.")
        return

    all_deltas = []
    for f in files:
        week = f.stem.replace("prediction_", "")
        try:
            all_deltas.append(run_week(week))
        except FileNotFoundError as e:
            print(f"Skipping {week}: {e}")

    if all_deltas:
        tot_d = sum(d["direction_hits"] for d in all_deltas)
        tot_r = sum(d["range_hits"]     for d in all_deltas)
        tot_a = sum(d["total_assets"]   for d in all_deltas)
        print(f"\n{'='*60}")
        print("  RUNNING ACCURACY SUMMARY")
        print(f"{'='*60}")
        print(f"  Weeks tracked : {len(all_deltas)}")
        print(f"  Direction     : {tot_d}/{tot_a} ({round(tot_d/tot_a*100,1)}%)")
        print(f"  Range         : {tot_r}/{tot_a} ({round(tot_r/tot_a*100,1)}%)")
        print(f"{'='*60}\n")

# ── Hardcoded W24 fallback ────────────────────────────────────────────────────
W24_PREDICTION = {
    "week": "W24",
    "assets": {
        "SPX":     {"direction": "DOWN",    "range_low": -3.0, "range_high": -1.0},
        "NDX":     {"direction": "DOWN",    "range_low": -4.0, "range_high": -1.5},
        "IWM":     {"direction": "DOWN",    "range_low": -3.5, "range_high": -1.0},
        "Gold":    {"direction": "FLAT-UP", "range_low": -1.0, "range_high":  2.0},
        "WTI":     {"direction": "UP",      "range_low":  0.0, "range_high":  4.0},
        "VIX":     {"direction": "UP",      "range_low":  0.0, "range_high": 20.0},
        "Bitcoin": {"direction": "DOWN",    "range_low": -8.0, "range_high": -2.0},
    }
}
W24_ACTUALS = {
    "week": "W24",
    "assets": {
        "SPX":     {"actual_change":  0.46},
        "NDX":     {"actual_change":  2.17},
        "IWM":     {"actual_change":  3.93},
        "Gold":    {"actual_change": -2.90},
        "WTI":     {"actual_change": -6.25},
        "VIX":     {"actual_change": -6.25},
        "Bitcoin": {"actual_change":  5.24},
    }
}

# ── Main ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evidence Agent — Delta Engine")
    parser.add_argument("--week",      type=str,        help="Week to compute e.g. W24")
    parser.add_argument("--all",       action="store_true", help="Compute all available weeks")
    parser.add_argument("--hardcoded", action="store_true", help="Run W24 from hardcoded data")
    args = parser.parse_args()

    if args.hardcoded or (not args.week and not args.all):
        print("Running W24 from hardcoded data...")
        delta = compute_delta(W24_PREDICTION, W24_ACTUALS)
        print_report(delta)
        md = generate_evidence_md(delta)
        print("\n--- GENERATED evidence_W24.md ---\n")
        print(md)
    elif args.all:
        run_all()
    elif args.week:
        try:
            run_week(args.week)
        except FileNotFoundError as e:
            print(f"Error: {e}")
