"""Markdown rendering for evidence reports."""

from __future__ import annotations

from datetime import date
from typing import Any, Final

EM_DASH: Final[str] = "\u2014"
PROJECT_WEEK_OFFSET: Final[int] = 20


class EvidenceReportRenderer:
    def render(self, snapshot: Any) -> str:
        project_week = self._project_week_number(snapshot.prediction_date)
        available_sectors = [
            sector for sector in snapshot.sectors if sector.weekly_change is not None
        ]
        sector_rows = self._render_sector_rows(snapshot.sectors)
        best_sector_lines = self._render_sector_summary(available_sectors[:3])
        worst_sector_lines = self._render_sector_summary(list(reversed(available_sectors[-3:])))
        screenshot_rows = self._render_screenshot_rows(snapshot)
        source_lines = self._render_source_lines(snapshot)

        return f"""# Week {project_week:02d} Market Report ({snapshot.week_end.year})

**Week ended:** {self._format_full_date(snapshot.week_end)}  
**Days the market was open:** {snapshot.open_days}

This file lists how the main markets moved last week. **Closing value** = price at the end of Friday. **Weekly change** = up or down for the whole week.

---

## Main Stock Indexes (3 we track)

These are the big U.S. stock benchmarks we score each week.

| What it is | Short name | Price at Friday close | Up or down this week |
|------------|------------|----------------------|----------------------|
{self._render_index_rows(snapshot.indexes)}

**In plain words:** {self._plain_words_indexes(snapshot.indexes)}

---

## Other Important Markets

Gold, oil, bonds, fear gauge (VIX), and crypto.

| What it is | Friday close | Up or down this week |
|------------|--------------|----------------------|
| {snapshot.gold.spec.label} | {self._format_close(snapshot.gold)} | **{self._format_direction(snapshot.gold.weekly_change)}** |
| {snapshot.oil.spec.label} | {self._format_close(snapshot.oil)} | **{self._format_direction(snapshot.oil.weekly_change)}** |
| **10-Year interest rate** | {self._format_yield_close(snapshot.ten_year)} | **{self._format_yield_direction(snapshot.ten_year.weekly_change_points)}** |
| {snapshot.bonds.spec.label} | {self._format_close(snapshot.bonds)} | **{self._format_direction(snapshot.bonds.weekly_change)}** |
| {snapshot.vix.spec.label} | {self._format_close(snapshot.vix)} | **{self._format_direction(snapshot.vix.weekly_change)}** |
| {snapshot.bitcoin.spec.label} | {self._format_close(snapshot.bitcoin)} | **{self._format_direction(snapshot.bitcoin.weekly_change)}** |

**In plain words:** {self._plain_words_other_markets(snapshot)}

---

## 11 Parts of the Stock Market (S&P sectors)

Each row is one industry group in the S&P 500.

| Rank | Industry group | Up or down this week |
|------|----------------|----------------------|
{sector_rows}

### Best 3 this week
{best_sector_lines}

### Worst 3 this week
{worst_sector_lines}

**In plain words:** {self._plain_words_sectors(snapshot.sectors)}

---

## Charts & Screenshots

Saved in the **evidence** folder:

| What the picture shows | File name |
|------------------------|-----------|
{screenshot_rows}

## Where the numbers came from

{source_lines}
"""

    @staticmethod
    def _project_week_number(prediction_date: date) -> int:
        project_week = prediction_date.isocalendar().week - PROJECT_WEEK_OFFSET
        return project_week if project_week > 0 else prediction_date.isocalendar().week

    def _render_screenshot_rows(self, snapshot: Any) -> str:
        rows = [
            (
                "| 1-week performance (Finviz) | "
                f" |"
            ),
            (
                "| S&P 500 map by sector (Finviz) | "
                f" |"
            ),
        ]
        rows.extend(
            f"| {label} | [{path}]({path}) |"
            for label, path in snapshot.technical_chart_links
        )
        return "\n".join(rows)

    def _render_source_lines(self, snapshot: Any) -> str:
        sources = [
            "- Finviz futures performance screenshot for 1-week cross-market visual evidence",
            "- Finviz S&P 500 sector map screenshot for sector visual evidence",
            "- Yahoo Finance adjusted daily close data via yfinance for SPX (^GSPC), NDX (^NDX), IWM, Gold (GC=F), Oil (CL=F), TLT, VIX (^VIX), Bitcoin (BTC-USD), and sector ETFs",
            "- 10-year Treasury yield from FRED series DGS10",
            "- Sector ETF proxies: XLK, XLE, XLF, XLY, XLP, XLI, XLB, XLV, XLU, XLRE, XLC",
        ]
        if snapshot.technical_chart_links:
            sources.append(
                "- ProRealTime daily chart screenshots generated by the technical agent under data/charts"
            )
        sources.append(f"- Sources accessed: {self._format_full_date(date.today())}")
        return "\n".join(sources)

    @staticmethod
    def _format_full_date(value: date) -> str:
        return f"{value:%A}, {value:%B} {value.day}, {value.year}"

    def _render_index_rows(self, indexes: list[Any]) -> str:
        return "\n".join(
            (
                f"| {move.spec.label} | {move.spec.short_name} | "
                f"{self._format_close(move)} | **{self._format_direction(move.weekly_change)}** |"
            )
            for move in indexes
        )

    def _render_sector_rows(self, sectors: list[Any]) -> str:
        rows = []
        for rank, sector in enumerate(sectors, start=1):
            direction = self._format_direction(sector.weekly_change)
            if sector.weekly_change is not None and (rank <= 3 or rank > len(sectors) - 3):
                direction = f"**{direction}**"
            rows.append(f"| {rank} | {sector.spec.name} | {direction} |")
        return "\n".join(rows)

    def _render_sector_summary(self, sectors: list[Any]) -> str:
        if not sectors:
            return "No sector ETF data was available from Yahoo Finance for this completed week."
        return "\n".join(
            (
                f"{rank}. **{sector.spec.name}** {EM_DASH} "
                f"{self._format_direction_sentence(sector.weekly_change)}. "
                f"Move based on {sector.spec.description} via {sector.spec.ticker}."
            )
            for rank, sector in enumerate(sectors, start=1)
        )

    @staticmethod
    def _format_direction(value: float | None) -> str:
        if value is None:
            return "N/A"
        if value > 0:
            return f"Up {abs(value):.2f}%"
        if value < 0:
            return f"Down {abs(value):.2f}%"
        return "Flat 0.00%"

    @staticmethod
    def _format_direction_sentence(value: float | None) -> str:
        if value is None:
            return "N/A"
        if value > 0:
            return f"up {abs(value):.2f}%"
        if value < 0:
            return f"down {abs(value):.2f}%"
        return "flat 0.00%"

    @staticmethod
    def _format_yield_direction(change_points: float | None) -> str:
        if change_points is None:
            return "N/A"
        if abs(change_points) < 0.01:
            return "Flat (about 0.00 points)"
        direction = "Slightly higher" if change_points > 0 else "Slightly lower"
        return f"{direction} (about {abs(change_points):.2f} points)"

    @staticmethod
    def _format_close(move: Any) -> str:
        if move.close is None:
            return "N/A"
        if move.spec.close_kind == "gold":
            return f"${move.close:,.0f} per ounce"
        if move.spec.close_kind == "oil":
            return f"${move.close:,.2f} per barrel"
        if move.spec.close_kind == "bitcoin":
            return f"${move.close:,.0f}"
        if move.spec.close_kind == "vix":
            return f"{move.close:,.2f}"
        return f"{move.close:,.2f}"

    @staticmethod
    def _format_yield_close(move: Any) -> str:
        if move.close is None:
            return "N/A"
        return f"{move.close:.2f}%"

    def _plain_words_indexes(self, indexes: list[Any]) -> str:
        available = [move for move in indexes if move.weekly_change is not None]
        if not available:
            return "Yahoo Finance index table data was not available for this completed week. The saved Finviz 1-week screenshot is the visual evidence source."

        up_count = sum(1 for move in available if move.weekly_change and move.weekly_change > 0)
        down_count = sum(1 for move in available if move.weekly_change and move.weekly_change < 0)
        best = max(available, key=lambda move: move.weekly_change or 0.0)
        worst = min(available, key=lambda move: move.weekly_change or 0.0)

        if up_count == len(available):
            lead = f"All {len(available)} available index readings finished higher."
        elif down_count == len(available):
            lead = f"All {len(available)} available index readings finished lower."
        else:
            lead = f"{up_count} of {len(available)} available index readings rose and {down_count} fell."

        return (
            f"{lead} {best.spec.short_name} led with a "
            f"{self._format_direction_sentence(best.weekly_change)} move, while "
            f"{worst.spec.short_name} was the weakest at "
            f"{self._format_direction_sentence(worst.weekly_change)}."
        )

    def _plain_words_other_markets(self, snapshot: Any) -> str:
        if snapshot.vix.weekly_change is None:
            fear = "was unavailable"
        else:
            fear = "eased" if snapshot.vix.weekly_change < 0 else "rose"
        oil_direction = self._format_direction_sentence(snapshot.oil.weekly_change)
        bitcoin_direction = self._format_direction_sentence(snapshot.bitcoin.weekly_change)
        bond_direction = self._format_direction_sentence(snapshot.bonds.weekly_change)
        if snapshot.ten_year.weekly_change_points is None:
            yield_direction = "was unavailable"
        elif abs(snapshot.ten_year.weekly_change_points) < 0.01:
            yield_direction = "was little changed"
        elif snapshot.ten_year.weekly_change_points < 0:
            yield_direction = "edged down"
        else:
            yield_direction = "edged up"

        return (
            f"Fear {fear} as VIX moved {self._format_direction_sentence(snapshot.vix.weekly_change)}. "
            f"Oil was {oil_direction}, Bitcoin was {bitcoin_direction}, and bonds were "
            f"{bond_direction} as the 10-year yield {yield_direction}."
        )

    def _plain_words_sectors(self, sectors: list[Any]) -> str:
        available = [sector for sector in sectors if sector.weekly_change is not None]
        if not available:
            return "Yahoo Finance sector ETF table data was not available for this completed week. The saved Finviz sector map screenshot is the visual evidence source."

        positive_count = sum(1 for sector in available if sector.weekly_change and sector.weekly_change > 0)
        best = available[0]
        worst = available[-1]
        breadth = (
            "a broad rally"
            if positive_count >= 8
            else "a mixed market"
            if positive_count >= 4
            else "a defensive or weak tape"
        )
        return (
            f"Sector breadth showed {breadth}: {positive_count} of {len(available)} available sectors finished green. "
            f"{best.spec.name} led at {self._format_direction_sentence(best.weekly_change)}, "
            f"while {worst.spec.name} lagged at {self._format_direction_sentence(worst.weekly_change)}."
        )